Repository EternalQuasar0206/Cli.NET, pull requests merged in 2022-06, with the labels that each got.

#4 Remade to accept different commands separated by &&
  Cli.NET/Cli.NET/Tools/CommandContainer.cs
Labels: bug, enhancement

#5 Chore: 2.1.0 Implementations
  Cli.NET/Cli.NET/Tools/CommandContainer.cs
  Package.nuspec
Labels: enhancement

#6 Changed the dependency package to be inside the main project
  .github/workflows/build_upload_nuget_package.yml
  Cli.NET/Cli.NET.Abstractions/Cli.NET.Abstractions.csproj
  Cli.NET/Cli.NET.Console/Cli.NET.Console.csproj
  Cli.NET/Cli.NET.sln
  Cli.NET/Cli.NET/Actions/ClearCommand.cs
  Cli.NET/Cli.NET/Actions/EchoCommand.cs
  Cli.NET/Cli.NET/Actions/ExitCommand.cs
  Cli.NET/Cli.NET/Actions/SumCommand.cs
  Cli.NET/Cli.NET/Cli.NET.csproj
  Cli.NET/Cli.NET/Interfaces/ICommand.cs
  Cli.NET/Cli.NET/Models/CommandList.cs
  Cli.NET/Cli.NET/Tools/CommandContainer.cs
Labels: enhancement

#7 Package: .nuspec package fix implementations
  .gitignore
  Cli.NET/Cli.NET.Console/Cli.NET.Console.csproj
  Cli.NET/Cli.NET.Console/Program.cs
  Cli.NET/Cli.NET.sln
  Cli.NET/Cli.NET/Cli.NET.csproj
  Package.nuspec
Labels: bug, enhancement

#10 Feat: ExecuteEnvironmentCommands() method
  Cli.NET/Cli.NET.sln
  Cli.NET/Cli.NET/Cli.NET.csproj
  Cli.NET/Cli.NET/Tools/CommandContainer.cs
  README.MD
Labels: enhancement

#11 Feat: 2.2.0-alpha
  Cli.NET/Cli.NET.sln
  Cli.NET/Cli.NET/Cli.NET.csproj
  Cli.NET/Cli.NET/Models/LambdaCommandList.cs
  Cli.NET/Cli.NET/Tools/CommandContainer.cs
  README.MD
Labels: enhancement

#12 Development: Documentation information
  Docs/CancellingTheLoopFlow.md
  Docs/CliDotNetCLNConsoleClassTools.md
  Docs/CreatingCommand.md
  Docs/CustomizingConsoleAppearance.md
  Docs/InitializingCommandListener.md
  Docs/ManagingOutputsExceptions.md
  Docs/PredefinedBuiltInCommands.md
  README.MD
Labels: documentation
